# Generated by Django 5.2.3 on 2025-07-28 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('science', 'Science'), ('programming', 'Programming'), ('language', 'Language Arts'), ('history', 'History'), ('custom', 'Custom Subject')], max_length=20)),
                ('context_text', models.TextField(blank=True, null=True)),
                ('context_file', models.FileField(blank=True, null=True, upload_to='subject_contexts/')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_contexts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Subject Contexts',
                'unique_together': {('user', 'subject')},
            },
        ),
    ]
